-- =================================================================
-- AegisFin Analytics Suite: 03_customer_analysis.sql
-- Customer Demographics, Velocity & Balance Concentration
-- =================================================================

-- Query 8: Active Customer Activity Rates
-- Calculates proportion of customers transacting 1, 2, 3, or 4+ times.
WITH customer_frequency AS (
    SELECT 
        customer_id,
        COUNT(transaction_id) AS tx_count
    FROM transactions
    GROUP BY customer_id
)
SELECT 
    CASE 
        WHEN tx_count = 1 THEN '1 Transaction'
        WHEN tx_count = 2 THEN '2 Transactions'
        WHEN tx_count = 3 THEN '3 Transactions'
        ELSE '4+ Transactions'
    END AS activity_frequency_tier,
    COUNT(customer_id) AS customer_count,
    ROUND(COUNT(customer_id) * 100.0 / (SELECT COUNT(DISTINCT customer_id) FROM transactions), 2) AS pct_of_customers
FROM customer_frequency
GROUP BY 1
ORDER BY 1 ASC;

-- Query 9: Top 20 Customers by Cumulative Transaction Value
-- Ranks customers by total monetary spend with running percentage.
SELECT 
    customer_id,
    location,
    tx_count,
    total_spend AS total_spend_inr,
    account_balance AS current_account_balance_inr,
    DENSE_RANK() OVER (ORDER BY total_spend DESC) AS spend_rank
FROM customers
ORDER BY total_spend DESC
LIMIT 20;

-- Query 10: Customer Concentration Analysis (Pareto Distribution)
-- Evaluates the percentage of transaction value generated by top 10% and top 20% of customers.
WITH customer_totals AS (
    SELECT 
        customer_id,
        SUM(transaction_amount) AS total_val,
        NTILE(10) OVER (ORDER BY SUM(transaction_amount) DESC) AS decile
    FROM transactions
    GROUP BY customer_id
)
SELECT 
    decile,
    COUNT(customer_id) AS customer_count,
    ROUND(SUM(total_val), 2) AS decile_total_spend_inr,
    ROUND(SUM(total_val) * 100.0 / (SELECT SUM(transaction_amount) FROM transactions), 2) AS spend_share_pct
FROM customer_totals
GROUP BY decile
ORDER BY decile ASC;

-- Query 11: Demographic Behavior Analysis by Gender
-- Analyzes transaction volume, avg spend, and balance across genders.
SELECT 
    gender,
    COUNT(c.customer_id) AS customer_count,
    ROUND(AVG(c.total_spend), 2) AS avg_customer_total_spend_inr,
    ROUND(AVG(c.account_balance), 2) AS avg_account_balance_inr,
    ROUND(AVG(c.tx_count), 2) AS avg_transactions_per_cust
FROM customers c
GROUP BY gender
ORDER BY customer_count DESC;

-- Query 12: Demographic Behavior Analysis by Age Group
-- Bins customers into age brackets (18-25, 26-35, 36-50, 51-65, 65+)
SELECT 
    CASE 
        WHEN age_imputed BETWEEN 18 AND 25 THEN '1. Young Adult (18-25)'
        WHEN age_imputed BETWEEN 26 AND 35 THEN '2. Early Career (26-35)'
        WHEN age_imputed BETWEEN 36 AND 50 THEN '3. Mid Career (36-50)'
        WHEN age_imputed BETWEEN 51 AND 65 THEN '4. Mature (51-65)'
        ELSE '5. Senior (65+)'
    END AS age_group,
    COUNT(customer_id) AS customer_count,
    ROUND(AVG(total_spend), 2) AS avg_spend_inr,
    ROUND(AVG(account_balance), 2) AS avg_balance_inr,
    ROUND(SUM(total_spend), 2) AS total_group_spend_inr
FROM customers
GROUP BY 1
ORDER BY 1 ASC;

-- Query 13: Customer Balance vs. Transaction Activity Correlation
-- Checks if high-balance customers transact more frequently.
SELECT 
    CASE 
        WHEN account_balance = 0 THEN '1. Zero Balance'
        WHEN account_balance < 10000 THEN '2. Low (< ₹10k)'
        WHEN account_balance BETWEEN 10000 AND 50000 THEN '3. Medium (₹10k - ₹50k)'
        WHEN account_balance BETWEEN 50000.01 AND 200000 THEN '4. High (₹50k - ₹200k)'
        ELSE '5. HNI (₹200k+)'
    END AS balance_tier,
    COUNT(customer_id) AS customer_count,
    ROUND(AVG(tx_count), 2) AS avg_tx_per_customer,
    ROUND(AVG(total_spend), 2) AS avg_spend_per_customer
FROM customers
GROUP BY 1
ORDER BY 1 ASC;
